spring.application.name=grupo_i

spring.datasource.url=jdbc:h2:mem:grupoidb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always